name: Build policies
on:
  - pull_request
  - push
jobs:
  docs:
    uses: "pedro-psb/.github/workflows/docs-ci.yml@update-ci-to-use-fetch"

  centos:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        centos:
          - "quay.io/centos/centos:stream9"
    container:
      image: ${{ matrix.centos }}
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: yum install -y selinux-policy-devel policycoreutils
      - name: Build policies
        run: |
          make -f /usr/share/selinux/devel/Makefile pulpcore_port.pp
          make -f /usr/share/selinux/devel/Makefile pulpcore.pp
          make -f /usr/share/selinux/devel/Makefile pulpcore_rhsmcertd.pp
